version: '3.1'
services:
  db:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: db_user
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  service-1:
    build:
      context: ./
      dockerfile: ./service-1/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./service-1/.env
    depends_on:
      - db
  service-2:
    build:
      context: ./
      dockerfile: ./service-2/Dockerfile
    container_name: service-2
    ports:
      - "3001:3001"
    env_file:
      - ./service-2/.env
    depends_on:
      - db
volumes:
  pgdata:
networks:
  localnetwork:
    external: true